# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            GolangVan
tagline:          'For Gophers in Vancouver'
description:      'The frontpage for the GolangVan meetup group'
url:              http://golangvan.org

author:
  name:           'Jingwen Owen Ou'
  url:            https://twitter.com/JingwenOwenOu

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jingweno/golangvan
